spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  profiles:
    active: loadInitialData
  h2:
    console:
      enabled: true
server:
  port: 1337
